// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_LabelCurrent;
extern lv_obj_t *ui_LabelVoltage;
extern lv_obj_t *ui_LabelEnergy;
extern lv_obj_t *ui_LabelPower;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_LabelOnOff;
extern lv_obj_t *ui_LabelCVCC;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

